### ISSUE TITLE
Unreachable URLs in `status` of `RawDeployment` `InferenceService`

### ISSUE THREAD

**Issue by phoevos** [canonical/kserve-operators#148]
Creating an example InferenceService in `RawDeployment` mode I get the following:
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    sidecar.istio.io/inject: "false"
  name: sklearn-iris
  namespace: test
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: gs://kfserving-examples/models/sklearn/1.0/model
status:
  address:
    url: http://sklearn-iris.test.svc.cluster.local
  components:
    predictor:
      [...]
      url: http://sklearn-iris-predictor-default-test.example.com
  [...]
  url: http://sklearn-iris-test.example.com
```

Running from inside a Notebook I can't hit either one of the provided URLs:
* http://sklearn-iris.test.svc.cluster.local (the corresponding K8s service does not exist in `RawDeployment` mode)
* http://sklearn-iris-predictor-default-test.example.com
* http://sklearn-iris-test.example.com

Reading through the docs it is not clear which one we should be using to perform inference from inside the cluster.
