### ISSUE TITLE
Hardcoded S3 details in integration with MinIO

### ISSUE THREAD

**Issue by misohu** [canonical/kserve-operators#186]
### Bug Description

To make make kserve integration with mlflow we are creating [object-storage secret ](https://github.com/canonical/kserve-operators/pull/184/files#diff-f0a46c9848b2ae1ebd02908eb723b34832ac7331d5550dcf474a13231be1179b) with annotations:

```
annotations:
     serving.kserve.io/s3-endpoint: "{{ s3_endpoint }}"
     serving.kserve.io/s3-usehttps: "{{ s3_usehttps }}"
     serving.kserve.io/s3-region: "{{ s3_region }}"
     serving.kserve.io/s3-useanoncredential: "{{s3_useanoncredential }}"
```
From these last three ones are not needed for integration with minio, but can't be committed in the secret (we will also need them in the future connecting to other object storage providers e.g. S3).

For now we keep them as constants in the `src\charm.py` file. 

For its meaning refer to the [upstream documentation ](https://kserve.github.io/website/0.11/modelserving/storage/s3/s3/).

**Important finding**. Kserve inference service will prefix the `serving.kserve.io/s3-endpoint` value with `http:\\` or `https:\\` based on value of `serving.kserve.io/s3-usehttps`.

### To Reproduce

None

### Environment

None

### Relevant Log Output

```shell
None
```
