### ISSUE TITLE
Upgrade Kserve to v0.11.1 for 1.8 release

### ISSUE THREAD

**Issue by misohu** [canonical/kserve-operators#193]
### What needs to get done

To correctly update the kserve to v0.11.1 for 1.8 release we need to 

- Update the images based on the information from this [PR](https://github.com/kubeflow/manifests/pull/2552/files).
- Generate the upstream `kustomize` manifests ([instructions](https://github.com/kubeflow/manifests/tree/v1.8-branch#kserve)) and compere them with ours.

At the end make sure the tests are passing.

### Why it needs to get done

Required for 1.8

**Comment by misohu** [comment]
In order to change the pmmlserver rock to upstream Docker I had to change the SrvingRuntime for pmmlserver in `serving_runtimes_manifests.yaml.j2` 

from:
```
  - args:
    - --args 
    - pmml-server
    - --model_name={{ '{{.Name}}' }}
    - --model_dir=/mnt/models
 ```
 to 
 ```
- args:
    - --model_name={{ '{{.Name}}' }}
    - --model_dir=/mnt/models
    - --http_port=8080
 ```

**Comment by misohu** [comment]
After upgrading the crds I tried to deploy following inference service 
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "pmml-demo"
spec:
  predictor:
    model:
      modelFormat:
        name: pmml
      storageUri: "gs://kfserving-examples/models/pmml"
      resources:
        limits:
          cpu: 1
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 250Mi
```

Getting 
```
Error from server (InternalError): error when retrieving current configuration of:
Resource: "serving.kserve.io/v1beta1, Resource=inferenceservices", GroupVersionKind: "serving.kserve.io/v1beta1, Kind=InferenceService"
Name: "pmml-demo", Namespace: "test"
from server for: "pmml-server.yaml": Internal error occurred: error resolving resource
```
